AWSTemplateFormatVersion: 2010-09-09
Description: Template for EC2 instances

# Metadata: 

Parameters:
  # VAR_PARAM_OS
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: VAR_AZ
  SubnetType:
    Type: String
    AllowedValues:
      - Private
      - Public
    Default: VAR_NETWORK
  # VAR_PARAM_ROLE

# Mappings created by CB #
Mappings:
# VAR_AMI_MAP
# VAR_SUBNET_MAP


Conditions: 
  CreateEIP: !Equals [ !Ref SubnetType, Public]

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: VAR_ROOT_VOL_NAME
          Ebs:
            VolumeSize: 64
            Encrypted: true
# VAR_PARAM_DISKS
      IamInstanceProfile: VAR_ROLE
      ImageId: !FindInMap [AMIMap, VAR_REGION, VAR_OS]
      InstanceType: VAR_INSTANCE_TYPE
      KeyName: VAR_KEYNAME
      SecurityGroupIds: VAR_SECURITY_GROUPS
      SubnetId: !FindInMap [SubnetMap, !Ref AvailabilityZone, VAR_NETWORK]
      Tags:
        - Key: Name
          Value: "VAR_HOSTNAME"
# VAR_UD
  ElasticIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIP
    Properties:
      Domain: vpc
      InstanceId: !Ref myEC2Instance

  # END OF RESOURCES

Outputs:
  PrivateIP:
    Value: !GetAtt
      - myEC2Instance
      - PrivateIp
  PublicIP:
    Condition: CreateEIP
    Value: !GetAtt
      - myEC2Instance
      - PublicIp
  

  # END OF OUTPUTS