AWSTemplateFormatVersion: 2010-09-09
Description: Template for EC2 instances

# Metadata: 

Parameters:
  OS:
    Type: String
    AllowedValues:
      - ubuntu16
      - ubuntu18
      - suse
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: VAR_REGIONa
  SubnetType:
    Type: String
    AllowedValues:
      - Private
      - Public
    Default: Private
  IamInstanceProfile:
    Type: String
    Default: EC2-S3-Access

# Mappings will need to be created by CB #
Mappings:
  AMIMap:
    us-east-2:
      ubuntu16: ami-0564dd36709a7a5b2
      ubuntu18: ami-0e8d1a9b450baa691
      suse: ami-0eb964f1cd28eb94d
# Subnetmap function will need to be scoped down to region
  SubnetMap:
    us-east-2a:
      Public: subnet-0ca766e0aba0bb36e
      Private: subnet-09fad3f8b283a63ef
    us-east-2c:
      Public: subnet-08b783efe3bfed00e
      Private: subnet-070bc9c800825dbd2
    us-east-2b:
      Public: subnet-0947b6bebe5425ec2
      Private: subnet-0e0cc0412cd1417c7

Conditions: 
  CreateEIP: !Equals [ !Ref SubnetType, Public]

Resources: 
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 64
            Encrypted: true
        - DeviceName: /dev/xvdb
          Ebs:
            # WILL NEED TO FIX VOLUME INPUT
            VolumeSize: VAR_DATAB
            Encrypted: true
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !FindInMap [AMIMap, !Ref "OS"]
      InstanceType: VAR_INSTANCE_TYPE
      KeyName: VAR_KEYNAME
      SecurityGroupIds:
        - sg-0560f1f9aff2ce8bf
        - sg-0946fa03e2571cd62
      SubnetId: !FindInMap [SubnetMap, !Ref AvailabilityZone, !Ref SubnetType]
      Tags:
        - Key: Name
          Value: "VAR_HOSTNAME"
      UserData: !Base64 |
        #!/bin/bash -ex
        hostnamectl set-hostname VAR_HOSTNAME
        echo "VAR_USER" > /home/ubuntu/user.txt
        echo "VAR_TIMEZONE" > /home/ubuntu/timezone.txt
        timedatectl set-timezone VAR_TIMEZONE
        adduser "VAR_USER"
        cp -R /home/ubuntu/.ssh /home/VAR_USER/.ssh
        chown -R VAR_USER: /home/VAR_USER/
        echo "VAR_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/VAR_USER
        chage -I -1 -m 0 -M 99999 -E -1 VAR_USER
        echo "VAR_USER" > /home/VAR_USER/user.txt
        echo "VAR_TIMEZONE" > /home/VAR_USER/timezone.txt
        reboot now
  ElasticIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIP
    Properties:
      Domain: vpc
      InstanceId: !Ref myEC2Instance

  # END OF RESOURCES

Outputs:
  PrivateIP:
    Value: !GetAtt
      - myEC2Instance
      - PrivateIp

  # END OF OUTPUTS