AWSTemplateFormatVersion: 2010-09-09
Description: This is the beta template that will accept other resources
# Metadata: 

Parameters:
  OS:
    Type: String
    AllowedValues:
      - ubuntu16
      - ubuntu18
      - suse
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  SubnetType:
    Type: String
    AllowedValues:
      - Private
      - Public
    Default: Public

Mappings: 
  AMIMap:
    us-east-1:
      ubuntu18: ami-0042c75bb13991538
      suse: ami-07649adafc3374b17
    us-east-2:
      ubuntu16: ami-0564dd36709a7a5b2
      ubuntu18: ami-0e8d1a9b450baa691
      suse: ami-0eb964f1cd28eb94d
    us-west-2:
      ubuntu18: ami-04c29899aa9bf924a

  SubnetMap:
    us-east-2a:
      Private: subnet-09fad3f8b283a63ef
      Public: subnet-0ca766e0aba0bb36e
    us-east-2b:
      Private: subnet-0e0cc0412cd1417c7
      Public: subnet-0947b6bebe5425ec2
    us-east-2c:
      Private: subnet-070bc9c800825dbd2
      Public: subnet-08b783efe3bfed00e

# Conditions: 

Resources: 
  myEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !FindInMap [AMIMap, !Ref "AWS::Region", !Ref "OS"]
      InstanceType: t3.micro
      SubnetId: !FindInMap [SubnetMap, !Ref AvailabilityZone, !Ref SubnetType]


Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref myEC2Instance